apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zabbix-frontend
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/managed-by: argocd
spec:
  rules:
  - host: eliezer.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zabbix-frontend-svc
            port:
              number: 8080