apiVersion: v1
kind: ConfigMap
metadata:
  name: zbx-config
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/managed-by: argocd
data:
  zbx-server-host: "zabbix-server-svc"