apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/managed-by: argocd
type: Opaque
data:
  database: emFiYml4ZGI=
  user: emFiYml4dXNlcg==
  password: emFiYml4cGFzc3dvcmQ=
  root-password: emFiYml4cm9vdHBhc3N3b3Jk